### ISSUE TITLE
Get first level of projection only

### ISSUE THREAD

**Issue by Alvyre** [markshapiro/graphql-db-projection#1]
Hello!

first thank you for you work, it saves me a lot of time for my project!
I was wondering, how to parse ASTFields with your lib to get only first level fields (and transform multi level in first level). To be clear this is an example : 

this is a request I made in GraphiQL
```graphql
{
  My_item(id: "abcdefghijklmnoqlsnejngwd") {
    id
    name
    function {
      subfield1
      subfield2
    }
  }
}
```

by default I get this with your functions (`makeProjection` and `toMongoProjection`): 
`id: 1, name: 1, 'function.subfield1': 1, 'function.subfield2': 1`

I would like to have something similar to this: 
`id: 1, name: 1, 'function: 1`

I saw in your documentation that we can do that:

`@proj(projections: [])`

in our GraphQL schema, so I tried to make it work but this time I don't get my object at all so I can't make any request with its id as you suggest it here : 

`// but not posts as we explicitly omitted them because they are located in different collection`

May be I didn't get something or did something wrong, IDK for the moment.

The only workaround I've found is to do something like:

```graphql
function:            Function @proj(projection: "function")
```
in my Schema. It not seems to be a clean way to do it..
Do you have any ideas? thanks!

**Comment by markshapiro** [comment]
that's the right way to do it, the "projection" is meant to contain all absolute field paths (inside nested object) that you need from db to resolve that particular graphql field, "projections: []" is to be used when you need nothing from db.
I can add new directive `@final` (or `@firstLevel`) so that `function:           Function @final` will generate `function: 1`

**Comment by Alvyre** [comment]
Thank you for you answer! I don't know if my case is very common but if you want to do it I would appreciate!

thanks! and again: thanks for your work

**Comment by markshapiro** [comment]
I added `@all` directive for that

**Comment by Alvyre** [comment]
Thanks !
